### ISSUE TITLE
Update to Webpack 4

### ISSUE THREAD

**Issue by thomassuckow** [mikeerickson/todo-webpack-plugin#15]
```
(node:98783) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
TypeError: Cannot read property 'forEach' of undefined
    at reporter (/node_modules/todo-webpack-plugin/index.js:35:11)
    at compiler.plugin (/node_modules/todo-webpack-plugin/index.js:26:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:18:1)
```

**Comment by mikeerickson** [comment]
https://github.com/webpack/webpack/issues/6568

https://github.com/webpack-contrib/copy-webpack-plugin/issues/225

**Comment by mikeerickson** [comment]
Issue has been cleared with the [1.9 release](https://github.com/mikeerickson/todo-webpack-plugin/releases/tag/v1.9.0)
